services:
  mysql:
    image: mysql:latest
    container_name: agreement-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    networks:
      - networkagreement
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  springboot-app:
    image: harsh237/agreementsb1 # Make sure to build your Spring Boot image
    container_name: agreement-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://agreement-mysql:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      ALLOWED_ORIGIN: ${ALLOWED_ORIGIN}
    ports:
      - "8090:8080" # Exposing Spring Boot's port
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - networkagreement

networks:
  networkagreement:


