services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=agreement_db'
      - 'MYSQL_PASSWORD=Harsh@123'
      - 'MYSQL_ROOT_PASSWORD=Harsh@123'
      - 'MYSQL_USER=root'
    ports:
      - '3306:3306'
