services:
  mysql:
    image: mysql:latest
    container_name: agreement-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Harsh@123
      MYSQL_DATABASE: agreement_db
      MYSQL_PASSWORD: Harsh@123
    ports:
      - "3307:3306"


